/**:
   ros__parameters:
      mqtt_broker_ip_address: '192.168.0.105'
      mqtt_broker_port_address: 1883
      system_ip_address: '192.168.0.105'
      drone_id: '70001'
      camera_topic_name: 'camera/id_70001/image_raw'
      recognition_threshold: 0.7                            # ranges from 0.0 -> 1.0
      led_gpio_pin_1: 12
      led_gpio_pin_2: 13
      arduino_port: '/dev/ttyUSB0'
      arduino_baud_rate: 9600